### ISSUE TITLE
Возможность выбора фрейма в онлайне и одиночных сражениях

### ISSUE THREAD

**Issue by DeltaDesignRus** [KranX/Perimeter#19]
На данный момент можно выбирать лишь фракцию, цвет и клан. Но у каждой фракции по 2 фрейма, хотелось бы иметь возможность внутри фракции выбирать фрейм.

**Comment by Aidoneus** [comment]
Там и цвета неиспользованные были ещё. Ну или может это побочные эффекты от инвалидных значений цвета были, конечно... На П-Вики где-то записаны были. В общем, если реально настоящие цвета ещё есть – круто бы их тоже дать выбирать.
