### ISSUE TITLE
Вырезать Gamespy полностью

### ISSUE THREAD

**Issue by DeltaDesignRus** [KranX/Perimeter#49]
Поскольку им никто не пользуется, и у нас нет лицензии на его использование, следует от него избавиться.

**Comment by Xottab-DUTY** [comment]
Есть же RetroSpy, может на него заменить?

**Comment by IkaR49** [comment]
> Поскольку им никто не пользуется, и у нас нет лицензии на его использование, следует от него избавиться.

GameSpy как компания упразднен в 2013-2014. 

> Есть же RetroSpy, может на него заменить?

RetroSpy это серверная часть. SDK на клиенте должен быть оригинальным от GameSpy, емнип.

**Comment by Xottab-DUTY** [comment]
> RetroSpy это серверная часть. SDK на клиенте должен быть оригинальным от GameSpy, емнип.

Это тебе так кажется, потому что они сосредоточены на сервере и в readme у них только про сервер. Я поглядел по исходникам, у них там весь нужный код есть.

**Comment by IonAgorria** [comment]
I think for now the best is going to remove the gamespy stuff and once we have replaced DirectPlay 8 code and cleaned up implement something for public server listing
